server.port: 8081

logging.level.org.springframework.security: DEBUG

com:
  c4-soft:
    springaddons:
      security:
        issuers:
          - location: https://localhost:8443/realms/master
            authorities:
              claims:
                - realm_access.roles
                - resource_access.my-progression.roles
                - resource_access.account.roles
              caze: upper
              prefix: ROLE_
        cors:
          - path: /user
          - path: /admin
          - path: /auth